version: '2.2'

services:
  ldap-user-manager:
    image: wheelybird/ldap-user-manager:latest
    ports:
      - '80:80'      
      - '443:443'      
    environment:
      - SERVER_HOSTNAME=localhost
      - LDAP_URI=ldap://192.168.18.8:389
      - LDAP_BASE_DN=dc=ldapusermanager,dc=org
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=ldapusermanager,dc=org
      - LDAP_ADMIN_BIND_PWD=change_me
      - LDAP_IGNORE_CERT_ERRORS=true

volumes:
  openldap_data:
    driver: local
